FROM resin/%%RESIN_MACHINE_NAME%%-alpine-node:9

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install --production

COPY . ./

HEALTHCHECK --start-period=5s --timeout=2s --interval=3s --retries=1 \
    CMD if [ ! -e "/tmp/working" ]; then exit 1; fi

CMD ["node", "app.js"]
